/* ATUALIZA NOTA FISCAL */

CREATE VIEW V_NOTA_FISCAL AS
SELECT ID_NF, SUM(TOTAL) AS SOMA
FROM ITEM_NF 
GROUP BY ID_NF
GO

SELECT * FROM V_NOTA_FISCAL
WHERE ID_NF = 1000 
GO

CREATE VIEW V_CARGA_NF AS
SELECT IDNF, N.TOTAL TOTALNOTA, I.SOMA
FROM NOTA_FISCAL N
INNER JOIN V_NOTA_FISCAL I
ON IDNF = ID_NF
GO

SELECT * FROM V_CARGA_NF
GO

UPDATE V_CARGA_NF SET TOTALNOTA = SOMA
GO

/* REALIZANDO CONSULTA NO AMBIENTE OLTP */

SELECT C.NOME, C.SOBRENOME AS "CLIENTE", C.SEXO, 
N.DATA, N.IDNF, P.PRODUTO, N.TOTAL
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
ON C.IDCLIENTE = N.ID_CLIENTE
INNER JOIN ITEM_NF I
ON N.IDNF = I.ID_NF
INNER JOIN PRODUTO P
ON P.IDPRODUTO = I.ID_PRODUTO
ORDER BY 5
GO